import EmployeeCard from "@/components/EmployeeCard/EmployeeCard";

export default function Home() {
  const employees = [
    {
      name: "Shahnil",
      position: "Software Engineer",
      department: "Engineering",
      email: "shahnil@duck.com",
      phone: "+923199318897",
      location: "Karachi",
      employeeId: "EMP123456",
      hireDate: "2025",
      manager: "Potato",
      skills: ["JavaScript", "React", "Node.js", "Next.js"],
      imageUrl:
        "https://img.freepik.com/free-vector/mysterious-mafia-man-wearing-hat_52683-34829.jpg",
    },
    {
      name: "Bilal",
      position: "Frontend Developer",
      department: "UI/UX",
      email: "bilal@example.com",
      phone: "+923100000001",
      location: "Lahore",
      employeeId: "EMP000001",
      hireDate: "2023",
      manager: "Potato",
      skills: ["React", "Tailwind", "Figma"],
      imageUrl: "/",
    },
    {
      name: "Masood",
      position: "Backend Developer",
      department: "Engineering",
      email: "masood@example.com",
      phone: "+923100000002",
      location: "Islamabad",
      employeeId: "EMP000002",
      hireDate: "2022",
      manager: "Tomato",
      skills: ["Node.js", "Express", "MongoDB"],
      imageUrl: "/",
    },
    {
      name: "Ayesha",
      position: "Product Manager",
      department: "Product",
      email: "ayesha@example.com",
      phone: "+923100000003",
      location: "Karachi",
      employeeId: "EMP000003",
      hireDate: "2021",
      manager: "Potato",
      skills: ["Agile", "Scrum", "JIRA"],
      imageUrl: "/",
    },
    {
      name: "Zain",
      position: "DevOps Engineer",
      department: "Operations",
      email: "zain@example.com",
      phone: "+923100000004",
      location: "Peshawar",
      employeeId: "EMP000004",
      hireDate: "2020",
      manager: "Tomato",
      skills: ["Docker", "Kubernetes", "CI/CD"],
      imageUrl: "/",
    },
    {
      name: "Fatima",
      position: "UI Designer",
      department: "Design",
      email: "fatima@example.com",
      phone: "+923100000005",
      location: "Lahore",
      employeeId: "EMP000005",
      hireDate: "2021",
      manager: "Onion",
      skills: ["Figma", "Adobe XD", "Sketch"],
      imageUrl: "/",
    },
    {
      name: "Ali",
      position: "Mobile Developer",
      department: "Engineering",
      email: "ali@example.com",
      phone: "+923100000006",
      location: "Multan",
      employeeId: "EMP000006",
      hireDate: "2019",
      manager: "Garlic",
      skills: ["Flutter", "React Native", "Swift"],
      imageUrl: "/",
    },
    {
      name: "Hina",
      position: "HR Manager",
      department: "Human Resources",
      email: "hina@example.com",
      phone: "+923100000007",
      location: "Hyderabad",
      employeeId: "EMP000007",
      hireDate: "2020",
      manager: "Potato",
      skills: ["Recruitment", "Conflict Resolution"],
      imageUrl: "/",
    },
    {
      name: "Usman",
      position: "QA Engineer",
      department: "Quality Assurance",
      email: "usman@example.com",
      phone: "+923100000008",
      location: "Sialkot",
      employeeId: "EMP000008",
      hireDate: "2021",
      manager: "Tomato",
      skills: ["Selenium", "Cypress", "Postman"],
      imageUrl: "/",
    },
    {
      name: "Mariam",
      position: "Business Analyst",
      department: "Business",
      email: "mariam@example.com",
      phone: "+923100000009",
      location: "Karachi",
      employeeId: "EMP000009",
      hireDate: "2023",
      manager: "Onion",
      skills: ["Requirements Gathering", "BPMN", "JIRA"],
      imageUrl: "/",
    },
    
  ];

  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 p-8 pb-20 font-[family-name:var(--font-geist-sans)]">
      {employees.map((employee, index) => (
        <EmployeeCard key={index} employee={employee} />
      ))}
    </div>
  );
}
